---
title: 'MATH 427: Classification Trees'
author: Eric Friedlander
footer: "[🔗 MAT 427 - Spring 2025 -  Schedule](https://mat427sp25.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
  cache: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---


## Computational Set-Up

```{r}
library(tidyverse)
library(tidymodels)
library(dsbox) # dcbikeshare data
library(knitr)

tidymodels_prefer()

set.seed(427)
```



## Last Time {.smaller}

-   Decision trees for classification
-   What are the three performance metrics we look at to make splits?
    

## Data: Voter Frequency

[Info about data](https://github.com/fivethirtyeight/data/tree/master/non-voters)

```{r}
voter_data <- read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/non-voters/nonvoters_data.csv')

glimpse(voter_data)
```

## Cleaning Data: Missing Data

```{r}
voter_data |> 
  summarize(across(everything(), ~sum(is.na(.x)))) |> 
  pivot_longer(everything()) |> 
  filter(value > 0)
```

## Cleaning the Data: Q28, 29, 31

-   What should we do with question 28?
-   What should we do with question 29?
-   What should we do with question 31?

## Cleaning the Data

```{r}
voter_clean <- voter_data |> 
  select(-RespId, -weight) |> 
  mutate(across(Q28_1:Q29_10, ~as_factor(case_when(
    .x == 1 ~ "Yes",
    .x == -1 ~ "No",
    TRUE ~ "Never Asked"
  ))),
  Party_ID = as_factor(case_when(
    Q31 == 1 ~ "Strong Republican",
    Q31 == 2 ~ "Republican",
    Q32 == 1  ~ "Strong Democrat",
    Q32 == 2 ~ "Democrat",
    Q33 == 1 ~ "Lean Republican",
    Q33 == 2 ~ "Lean Democrat"
  )))
```

## Split Data

```{r}
set.seed(427)

voter_splits <- initial_split(voter_clean, prop = 0.7, strata = voter_category)
voter_train <- training(voter_splits)
voter_test <- testing(voter_splits)
```



# Classification Trees in R

